<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <artifactId>trails-service</artifactId>
    <build>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <artifactId>lombok</artifactId>
                            <groupId>org.projectlombok</groupId>
                            <version>${lombok.version}</version>
                        </path>
                        <path>
                            <artifactId>mapstruct-processor</artifactId>
                            <groupId>org.mapstruct</groupId>
                            <version>${mapstruct.version}</version>
                        </path>
                    </annotationProcessorPaths>
                    <release>25</release>
                    <source>25</source>
                    <target>25</target>
                </configuration>
                <groupId>org.apache.maven.plugins</groupId>
                <version>${maven-compiler-plugin.version}</version>
            </plugin>
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <argLine>${surefireArgLine}
                        -javaagent:${org.mockito:mockito-core:jar}
                        -Xshare:off
                    </argLine>
                    <useManifestOnlyJar>false</useManifestOnlyJar>
                    <excludes>
                        <exclude>**/*IT.java</exclude>
                    </excludes>
                </configuration>
                <groupId>org.apache.maven.plugins</groupId>
            </plugin>
            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <configuration>
                    <argLine>${failsafeArgLine}
                        -javaagent:${org.mockito:mockito-core:jar}
                        -Xshare:off
                    </argLine>
                    <classesDirectory>${project.build.outputDirectory}</classesDirectory>
                    <useManifestOnlyJar>false</useManifestOnlyJar>
                    <includes>
                        <include>**/*IT.java</include>
                    </includes>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
                <groupId>org.apache.maven.plugins</groupId>
            </plugin>
            <plugin>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>properties</goal>
                        </goals>
                        <phase>initialize</phase>
                    </execution>
                </executions>
                <groupId>org.apache.maven.plugins</groupId>
            </plugin>
            <plugin>
                <artifactId>jacoco-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <configuration>
                            <destFile>${project.build.directory}/jacoco-unit.exec</destFile>
                            <propertyName>surefireArgLine</propertyName>
                        </configuration>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                        <id>prepare-unit-tests</id>
                    </execution>
                    <execution>
                        <configuration>
                            <dataFile>${project.build.directory}/jacoco-unit.exec</dataFile>
                            <outputDirectory>${project.build.directory}/site/unit-test-report</outputDirectory>
                        </configuration>
                        <goals>
                            <goal>report</goal>
                        </goals>
                        <id>unit-report</id>
                        <phase>test</phase>
                    </execution>
                    <execution>
                        <configuration>
                            <destFile>${project.build.directory}/jacoco-it.exec</destFile>
                            <propertyName>failsafeArgLine</propertyName>
                        </configuration>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                        <id>prepare-integration-tests</id>
                        <phase>pre-integration-test</phase>
                    </execution>
                    <execution>
                        <configuration>
                            <dataFile>${project.build.directory}/jacoco-it.exec</dataFile>
                            <outputDirectory>${project.build.directory}/site/integration-test-report
                            </outputDirectory>
                        </configuration>
                        <goals>
                            <goal>report</goal>
                        </goals>
                        <id>integration-report</id>
                        <phase>verify</phase>
                    </execution>
                </executions>
                <groupId>org.jacoco</groupId>
                <version>${jacoco-maven-plugin.version}</version>
            </plugin>
            <plugin>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <artifactId>lombok</artifactId>
                            <groupId>org.projectlombok</groupId>
                        </exclude>
                    </excludes>
                </configuration>
                <groupId>org.springframework.boot</groupId>
            </plugin>
            <plugin>
                <groupId>io.spring.javaformat</groupId>
                <artifactId>spring-javaformat-maven-plugin</artifactId>
                <version>0.0.47</version>
                <executions>
                    <execution>
                        <phase>validate</phase>
                        <inherited>true</inherited>
                        <goals>
                            <goal>validate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <artifactId>openapi-generator-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <configuration>
                            <configOptions>
                                <interfaceOnly>true</interfaceOnly>
                                <java8>false</java8>
                                <modelPackage>io.github.yaforster.trails.adapter.api.rest.model</modelPackage>
                                <openApiNullable>false</openApiNullable>
                                <sourceFolder>src/gen/java/main</sourceFolder>
                                <useEnumAsRef>true</useEnumAsRef>
                                <useJackson3>true</useJackson3>
                                <useSpringBoot4>true</useSpringBoot4>
                                <useOneOfDiscriminatorLookup>true</useOneOfDiscriminatorLookup>
                                <useTags>true</useTags>
                            </configOptions>
                            <generatorName>spring</generatorName>
                            <inputSpec>src/main/resources/api/hateoas.yaml</inputSpec>
                            <modelNameSuffix>DTO</modelNameSuffix>
                            <openapiNormalizer>REF_AS_PARENT_IN_ALLOF=true</openapiNormalizer>
                            <typeMappings>Boolean=boolean</typeMappings>
                        </configuration>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <id>hateoas</id>
                    </execution>
                </executions>
                <groupId>org.openapitools</groupId>
                <version>${openapi-generator-maven-plugin.version}</version>
            </plugin>
            <plugin>
                <groupId>org.liquibase</groupId>
                <artifactId>liquibase-maven-plugin</artifactId>
                <version>${liquibase-maven-plugin.version}</version>
                <configuration>
                    <changeLogFile>src/main/resources/db/changelog/db.changelog-master.yaml</changeLogFile>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>com.mysql</groupId>
                        <artifactId>mysql-connector-j</artifactId>
                        <version>${mysql-connector-j.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>
    <dependencies>
        <dependency>
            <artifactId>swagger-annotations</artifactId>
            <groupId>io.swagger.core.v3</groupId>
            <version>${swagger-annotations.version}</version>
        </dependency>
        <dependency>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
            <groupId>org.springframework.boot</groupId>
        </dependency>
        <dependency>
            <artifactId>spring-boot-starter-validation</artifactId>
            <groupId>org.springframework.boot</groupId>
        </dependency>
        <dependency>
            <artifactId>spring-boot-starter-webmvc</artifactId>
            <groupId>org.springframework.boot</groupId>
        </dependency>
        <dependency>
            <artifactId>spring-boot-starter-aspectj</artifactId>
            <groupId>org.springframework.boot</groupId>
        </dependency>
        <dependency>
            <artifactId>spring-boot-starter-actuator</artifactId>
            <groupId>org.springframework.boot</groupId>
        </dependency>
        <dependency>
            <artifactId>resilience4j-spring-boot4</artifactId>
            <groupId>io.github.resilience4j</groupId>
            <version>${resilience4j.version}</version>
        </dependency>
        <dependency>
            <artifactId>spring-boot-starter-hateoas</artifactId>
            <groupId>org.springframework.boot</groupId>
        </dependency>
        <dependency>
            <artifactId>spring-boot-starter-security-oauth2-resource-server</artifactId>
            <groupId>org.springframework.boot</groupId>
        </dependency>
        <dependency>
            <artifactId>spring-boot-starter-security</artifactId>
            <groupId>org.springframework.boot</groupId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-thymeleaf</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-liquibase</artifactId>
        </dependency>
        <dependency>
            <artifactId>mysql-connector-j</artifactId>
            <groupId>com.mysql</groupId>
            <scope>runtime</scope>
            <version>${mysql-connector-j.version}</version>
        </dependency>
        <dependency>
            <artifactId>commons-collections4</artifactId>
            <groupId>org.apache.commons</groupId>
            <version>${commons-collections4.version}</version>
        </dependency>
        <dependency>
            <artifactId>selenium-api</artifactId>
            <groupId>org.seleniumhq.selenium</groupId>
        </dependency>
        <dependency>
            <artifactId>selenium-remote-driver</artifactId>
            <groupId>org.seleniumhq.selenium</groupId>
        </dependency>
        <dependency>
            <artifactId>selenium-chrome-driver</artifactId>
            <groupId>org.seleniumhq.selenium</groupId>
        </dependency>
        <dependency>
            <artifactId>selenium-edge-driver</artifactId>
            <groupId>org.seleniumhq.selenium</groupId>
        </dependency>
        <dependency>
            <artifactId>selenium-firefox-driver</artifactId>
            <groupId>org.seleniumhq.selenium</groupId>
        </dependency>
        <dependency>
            <artifactId>selenium-support</artifactId>
            <groupId>org.seleniumhq.selenium</groupId>
        </dependency>
        <dependency>
            <artifactId>commons-lang3</artifactId>
            <groupId>org.apache.commons</groupId>
            <version>${commons-lang3.version}</version>
        </dependency>
        <dependency>
            <artifactId>guava</artifactId>
            <groupId>com.google.guava</groupId>
            <version>${guava.version}</version>
        </dependency>
        <dependency>
            <artifactId>lombok</artifactId>
            <groupId>org.projectlombok</groupId>
            <optional>true</optional>
            <scope>provided</scope>
            <version>${lombok.version}</version>
        </dependency>
        <dependency>
            <artifactId>spring-boot-starter-test</artifactId>
            <groupId>org.springframework.boot</groupId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <artifactId>spring-boot-starter-webmvc-test</artifactId>
            <groupId>org.springframework.boot</groupId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <artifactId>archunit</artifactId>
            <groupId>com.tngtech.archunit</groupId>
            <scope>test</scope>
            <version>${archunit.version}</version>
        </dependency>
        <dependency>
            <artifactId>instancio-junit</artifactId>
            <groupId>org.instancio</groupId>
            <scope>test</scope>
            <version>${instancio-junit.version}</version>
        </dependency>
        <dependency>
            <artifactId>mockito-core</artifactId>
            <groupId>org.mockito</groupId>
            <scope>test</scope>
            <version>${mockito.version}</version>
        </dependency>
        <dependency>
            <artifactId>mapstruct</artifactId>
            <groupId>org.mapstruct</groupId>
            <version>${mapstruct.version}</version>
        </dependency>
        <dependency>
            <artifactId>h2</artifactId>
            <groupId>com.h2database</groupId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>com.openhtmltopdf</groupId>
            <artifactId>openhtmltopdf-core</artifactId>
            <version>${openhtml.version}</version>
        </dependency>

        <dependency>
            <groupId>com.openhtmltopdf</groupId>
            <artifactId>openhtmltopdf-pdfbox</artifactId>
            <version>${openhtml.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.pdfbox</groupId>
            <artifactId>pdfbox</artifactId>
            <version>${pdfbox.version}</version>
        </dependency>
    </dependencies>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <artifactId>selenium-bom</artifactId>
                <groupId>org.seleniumhq.selenium</groupId>
                <scope>import</scope>
                <type>pom</type>
                <version>${selenium-java.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <groupId>io.github.yaforster</groupId>
    <modelVersion>4.0.0</modelVersion>
    <packaging>jar</packaging>
    <parent>
        <artifactId>spring-boot-starter-parent</artifactId>
        <groupId>org.springframework.boot</groupId>
        <relativePath/>
        <version>4.0.6</version>
    </parent>
    <properties>
        <archunit.version>1.4.2</archunit.version>
        <commons-collections4.version>4.5.0</commons-collections4.version>
        <commons-lang3.version>3.20.0</commons-lang3.version>
        <guava.version>33.6.0-jre</guava.version>
        <instancio-junit.version>6.0.0-RC3</instancio-junit.version>
        <jacoco-maven-plugin.version>0.8.14</jacoco-maven-plugin.version>
        <lombok.version>1.18.46</lombok.version>
        <liquibase-maven-plugin.version>5.0.3</liquibase-maven-plugin.version>
        <mapstruct.version>1.6.3</mapstruct.version>
        <maven-compiler-plugin.version>3.15.0</maven-compiler-plugin.version>
        <mockito.version>5.23.0</mockito.version>
        <mysql-connector-j.version>9.7.0</mysql-connector-j.version>
        <openapi-generator-maven-plugin.version>7.22.0</openapi-generator-maven-plugin.version>
        <pdfbox.version>2.0.24</pdfbox.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <resilience4j.version>2.4.0</resilience4j.version>
        <selenium-java.version>4.44.0</selenium-java.version>
        <swagger-annotations.version>2.2.50</swagger-annotations.version>
        <openhtml.version>1.0.10</openhtml.version>
    </properties>
    <repositories>
        <repository>
            <id>central</id>
            <url>https://repo.maven.apache.org/maven2</url>
        </repository>
    </repositories>
    <version>0.0.5</version>
</project>
